export { default as CommunityPage } from "./CommunityPage"
export { default as SignUpPage } from "./SignUpPage"
export { default as WelcomePage } from "./WelcomePage/WelcomePage"
export { default as ProfilePage } from "./ProfilePage"
export {default as BookInfo} from "./BookInfo"